trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: devsecopsdemo

steps:

# ✅ Maven Compile + Test
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean compile test'

# ✅ SonarQube
- script: |
    mvn sonar:sonar \
    -Dsonar.projectKey=devsecops-demo \
    -Dsonar.host.url=http://20.2.88.28:9000 \
    -Dsonar.login=$(SONAR_TOKEN)

# ✅ Dependency Check (DO NOT FAIL PIPELINE)
- script: |
    mvn dependency-check:check
  continueOnError: true

# ✅ Build JAR
- script: mvn package

# ✅ Docker Build
- script: |
    docker build -t $(IMAGE_NAME):latest .

# ✅ Docker Login + Push (using secrets)
- script: |
    echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
    docker tag $(IMAGE_NAME):latest $(DOCKER_USERNAME)/$(IMAGE_NAME):latest
    docker push $(DOCKER_USERNAME)/$(IMAGE_NAME):latest

- script: |
    sudo apt-get update
    sudo apt-get install -y wget apt-transport-https gnupg lsb-release
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
    sudo apt-get update
    sudo apt-get install -y trivy

# ✅ Trivy Scan
- script: |
    trivy image $(DOCKER_USERNAME)/$(IMAGE_NAME):latest

# ✅ Deploy Container
- script: |
    docker run -d -p 8080:8080 $(DOCKER_USERNAME)/$(IMAGE_NAME):latest
